name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and Package
      run: mvn package

    - name: OWASP Dependency-Check
      run: |
        curl -fsSL -o dependency-check.sh https://owasp.org/www-project-dependency-check/
        chmod +x dependency-check.sh
        ./dependency-check.sh -f "JSON" -o "./dependency-check-report.json" -s .
      continue-on-error: true

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./dependency-check-report.json
